//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Negocio
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class gSatOrganogrmaRev2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new gSatOrganogrmaRev2 object using the connection string found in the 'gSatOrganogrmaRev2' section of the application configuration file.
        /// </summary>
        public gSatOrganogrmaRev2() : base("name=gSatOrganogrmaRev2", "gSatOrganogrmaRev2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new gSatOrganogrmaRev2 object.
        /// </summary>
        public gSatOrganogrmaRev2(string connectionString) : base(connectionString, "gSatOrganogrmaRev2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new gSatOrganogrmaRev2 object.
        /// </summary>
        public gSatOrganogrmaRev2(EntityConnection connection) : base(connection, "gSatOrganogrmaRev2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
